name = 
version = 
# "repository"
type = 
# "repository"
url = 
# "devDependencies"
bluebird = 
# "devDependencies"
eslint-plugin-google-camelcase = 
# "devDependencies"
google-closure-compiler = 
# "devDependencies"
grunt = 
# "devDependencies"
grunt-bump = 
# "devDependencies"
grunt-cli = 
# "devDependencies"
grunt-contrib-clean = 
# "devDependencies"
grunt-contrib-coffee = 
# "devDependencies"
grunt-contrib-copy = 
# "devDependencies"
grunt-contrib-qunit = 
# "devDependencies"
grunt-eslint = 
# "devDependencies"
grunt-prompt = 
# "devDependencies"
load-grunt-tasks = 
# "devDependencies"
superagent = 
# "scripts"
test = 
description = 
# "bugs"
url = 
homepage = 
main = 
# "directories"
test = 
# .list
keywords = 
author = 
license = 
// = \=/UserScript\=\=
//\ @name\ GoEar\ HotLink\ 2015 = 
//\ @author\ laurenceHR = 
//\ @include\ *goear.com/listen/* = 
//\ @include\ *goear.com/listen/*/* = 
//\ @version\ 1.5 = 
//\ @description\ Goear\ HotLink\ for\ download = 
//\ Script\ by\ laurenceHR\ -\ www.daxes.net = 
//////\ Get\ Song\ ID = 
var\ url = document.URL;
var\ urls = url.split('/');
var\ id = urls[4];
///////\ Get\ HotLink = 
var\ hotlink = "http\://www.goear.com/action/sound/get/" + id;
//////\ Add\ HotLink = 
addHotLink(hotlink); = 
////// = 
/******\ \ Function\ For\ Add\ Link\ *****/ = 
function\ addHotLink(link){ = 
//var\ style = document.createElement('style');
//var\ css = "\#main.listen .actions .down {background-position-y\: 8px;}" + "\n";
//\ \ \ \ style.textContent = css;
//var\ head = document.getElementsByTagName('head')[0];
//\ \ \ \ head.appendChild(style); = 
var\ a = document.createElement('a');
a.href = link;
a.target = "_blank";
a.innerHTML = '<span class\="glyphicons download"></span>';
a.title = 'Get HotLink';
a.className = '';
a.id = 'hotlink';
var\ li = document.createElement('li');
li.className = 'action_item';
li.appendChild(a); = 
var\ ul_actions = document.getElementsByClassName('actions')[0];
ul_actions.appendChild(li); = 
} = 
var\ express = require('express');
var\ path = 
var\ favicon = 
var\ logger = 
var\ cookieParser = 
var\ bodyParser = 
var\ index = 
var\ users = 
var\ app = 
//\ view\ engine\ setup = 
app.set('views',\ path.join(__dirname,\ 'views')); = 
app.set('view\ engine',\ 'jade'); = 
//\ uncomment\ after\ placing\ your\ favicon\ in\ /public = 
//app.use(favicon(path.join(__dirname,\ 'public',\ 'favicon.ico'))); = 
app.use(logger('dev')); = 
app.use(bodyParser.json()); = 
app.use(bodyParser.urlencoded({\ extended = 
app.use(cookieParser()); = 
app.use(express.static(path.join(__dirname,\ 'public'))); = 
app.use('/',\ index); = 
app.use('/users',\ users); = 
//\ catch\ 404\ and\ forward\ to\ error\ handler = 
app.use(function(req,\ res,\ next)\ { = 
var\ err = 
err.status = 
next(err); = 
}); = 
//\ error\ handler = 
app.use(function(err,\ req,\ res,\ next)\ { = 
//\ set\ locals,\ only\ providing\ error\ in\ development = 
res.locals.message = 
res.locals.error = 
//\ render\ the\ error\ page = 
res.status(err.status\ ||\ 500); = 
res.render('error'); = 
module.exports = (options) \=> {
# "repository"
type = 
# "bugs"
url = 
# "devDependencies"
bluebird = 
# "devDependencies"
eslint-plugin-google-camelcase = 
# "devDependencies"
google-closure-compiler = 
# "devDependencies"
grunt = 
# "devDependencies"
grunt-bump = 
# "devDependencies"
grunt-cli = 
# "devDependencies"
grunt-contrib-clean = 
# "devDependencies"
grunt-contrib-coffee = 
# "devDependencies"
grunt-contrib-copy = 
# "devDependencies"
grunt-contrib-qunit = 
# "devDependencies"
grunt-eslint = 
# "devDependencies"
grunt-prompt = 
# "devDependencies"
load-grunt-tasks = 
# "devDependencies"
superagent = 
# "directories"
test = 
# .list
keywords = 
var\ router = 
/*\ GET\ home\ page.\ */ = 
router.get('/',\ function(req,\ res,\ next)\ { = 
res.render('index',\ {\ title = 
repository = 
# "bin"
lightcrawler = 
# "dependencies"
async = 
# "dependencies"
cheerio = 
# "dependencies"
colors = 
# "dependencies"
lighthouse = 
# "dependencies"
simplecrawler = 
# "dependencies"
yargs = 
# "devDependencies"
express = 
# "devDependencies"
get-port = 
# "devDependencies"
mocha = 
# "devDependencies"
standard = 
# .list
files = 
lockfileVersion = 
# "dependencies"."@types/node"
version = 
# "dependencies"."@types/node"
resolved = 
# "dependencies"."@types/node"
integrity = 
# "dependencies"."accepts"
version = 
# "dependencies"."accepts"
resolved = 
# "dependencies"."accepts"
integrity = 
# "dependencies"."accepts"
dev = 
# "dependencies"."acorn"
version = 
# "dependencies"."acorn"
resolved = 
# "dependencies"."acorn"
integrity = 
# "dependencies"."acorn"
dev = 
# "dependencies"."acorn-jsx"
version = 
# "dependencies"."acorn-jsx"
resolved = 
# "dependencies"."acorn-jsx"
integrity = 
# "dependencies"."acorn-jsx"
dev = 
# "dependencies"."acorn-jsx"."dependencies"."acorn"
version = 
# "dependencies"."acorn-jsx"."dependencies"."acorn"
resolved = 
# "dependencies"."acorn-jsx"."dependencies"."acorn"
integrity = 
# "dependencies"."acorn-jsx"."dependencies"."acorn"
dev = 
# "dependencies"."ajv"
version = 
# "dependencies"."ajv"
resolved = 
# "dependencies"."ajv"
integrity = 
# "dependencies"."ajv"
dev = 
# "dependencies"."ajv-keywords"
version = 
# "dependencies"."ajv-keywords"
resolved = 
# "dependencies"."ajv-keywords"
integrity = 
# "dependencies"."ajv-keywords"
dev = 
# "dependencies"."ansi-align"
version = 
# "dependencies"."ansi-align"
resolved = 
# "dependencies"."ansi-align"
integrity = 
# "dependencies"."ansi-escapes"
version = 
# "dependencies"."ansi-escapes"
resolved = 
# "dependencies"."ansi-escapes"
integrity = 
# "dependencies"."ansi-escapes"
dev = 
# "dependencies"."ansi-regex"
version = 
# "dependencies"."ansi-regex"
resolved = 
# "dependencies"."ansi-regex"
integrity = 
# "dependencies"."ansi-styles"
version = 
# "dependencies"."ansi-styles"
resolved = 
# "dependencies"."ansi-styles"
integrity = 
# "dependencies"."argparse"
version = 
# "dependencies"."argparse"
resolved = 
# "dependencies"."argparse"
integrity = 
# "dependencies"."argparse"
dev = 
# "dependencies"."array-find-index"
version = 
# "dependencies"."array-find-index"
resolved = 
# "dependencies"."array-find-index"
integrity = 
# "dependencies"."array-flatten"
version = 
# "dependencies"."array-flatten"
resolved = 
# "dependencies"."array-flatten"
integrity = 
# "dependencies"."array-flatten"
dev = 
# "dependencies"."array-union"
version = 
# "dependencies"."array-union"
resolved = 
# "dependencies"."array-union"
integrity = 
# "dependencies"."array-union"
dev = 
# "dependencies"."array-uniq"
version = 
# "dependencies"."array-uniq"
resolved = 
# "dependencies"."array-uniq"
integrity = 
# "dependencies"."array-uniq"
dev = 
# "dependencies"."array.prototype.find"
version = 
# "dependencies"."array.prototype.find"
resolved = 
# "dependencies"."array.prototype.find"
integrity = 
# "dependencies"."array.prototype.find"
dev = 
# "dependencies"."arrify"
version = 
# "dependencies"."arrify"
resolved = 
# "dependencies"."arrify"
integrity = 
# "dependencies"."arrify"
dev = 
# "dependencies"."async"
version = 
# "dependencies"."async"
resolved = 
# "dependencies"."async"
integrity = 
# "dependencies"."axe-core"
version = 
# "dependencies"."axe-core"
resolved = 
# "dependencies"."axe-core"
integrity = 
# "dependencies"."babar"
version = 
# "dependencies"."babar"
resolved = 
# "dependencies"."babar"
integrity = 
# "dependencies"."babar"."dependencies"."colors"
version = 
# "dependencies"."babar"."dependencies"."colors"
resolved = 
# "dependencies"."babar"."dependencies"."colors"
integrity = 
# "dependencies"."babel-code-frame"
version = 
# "dependencies"."babel-code-frame"
resolved = 
# "dependencies"."babel-code-frame"
integrity = 
# "dependencies"."babel-code-frame"
dev = 
# "dependencies"."balanced-match"
version = 
# "dependencies"."balanced-match"
resolved = 
# "dependencies"."balanced-match"
integrity = 
# "dependencies"."balanced-match"
dev = 
# "dependencies"."boolbase"
version = 
# "dependencies"."boolbase"
resolved = 
# "dependencies"."boolbase"
integrity = 
# "dependencies"."boxen"
version = 
# "dependencies"."boxen"
resolved = 
# "dependencies"."boxen"
integrity = 
# "dependencies"."boxen"."dependencies"."camelcase"
version = 
# "dependencies"."boxen"."dependencies"."camelcase"
resolved = 
# "dependencies"."boxen"."dependencies"."camelcase"
integrity = 
# "dependencies"."boxen"."dependencies"."chalk"
version = 
# "dependencies"."boxen"."dependencies"."chalk"
resolved = 
# "dependencies"."boxen"."dependencies"."chalk"
integrity = 
# "dependencies"."brace-expansion"
version = 
# "dependencies"."brace-expansion"
resolved = 
# "dependencies"."brace-expansion"
integrity = 
# "dependencies"."brace-expansion"
dev = 
# "dependencies"."browser-stdout"
version = 
# "dependencies"."browser-stdout"
resolved = 
# "dependencies"."browser-stdout"
integrity = 
# "dependencies"."browser-stdout"
dev = 
# "dependencies"."builtin-modules"
version = 
# "dependencies"."builtin-modules"
resolved = 
# "dependencies"."builtin-modules"
integrity = 
# "dependencies"."caller-path"
version = 
# "dependencies"."caller-path"
resolved = 
# "dependencies"."caller-path"
integrity = 
# "dependencies"."caller-path"
dev = 
# "dependencies"."callsites"
version = 
# "dependencies"."callsites"
resolved = 
# "dependencies"."callsites"
integrity = 
# "dependencies"."callsites"
dev = 
# "dependencies"."camelcase"
version = 
# "dependencies"."camelcase"
resolved = 
# "dependencies"."camelcase"
integrity = 
# "dependencies"."camelcase-keys"
version = 
# "dependencies"."camelcase-keys"
resolved = 
# "dependencies"."camelcase-keys"
integrity = 
# "dependencies"."capture-stack-trace"
version = 
# "dependencies"."capture-stack-trace"
resolved = 
# "dependencies"."capture-stack-trace"
integrity = 
# "dependencies"."chalk"
version = 
# "dependencies"."chalk"
resolved = 
# "dependencies"."chalk"
integrity = 
# "dependencies"."chalk"."dependencies"."ansi-regex"
version = 
# "dependencies"."chalk"."dependencies"."ansi-regex"
resolved = 
# "dependencies"."chalk"."dependencies"."ansi-regex"
integrity = 
# "dependencies"."chalk"."dependencies"."ansi-styles"
version = 
# "dependencies"."chalk"."dependencies"."ansi-styles"
resolved = 
# "dependencies"."chalk"."dependencies"."ansi-styles"
integrity = 
# "dependencies"."chalk"."dependencies"."strip-ansi"
version = 
# "dependencies"."chalk"."dependencies"."strip-ansi"
resolved = 
# "dependencies"."chalk"."dependencies"."strip-ansi"
integrity = 
# "dependencies"."chalk"."dependencies"."supports-color"
version = 
# "dependencies"."chalk"."dependencies"."supports-color"
resolved = 
# "dependencies"."chalk"."dependencies"."supports-color"
integrity = 
# "dependencies"."cheerio"
version = 
# "dependencies"."cheerio"
resolved = 
# "dependencies"."cheerio"
integrity = 
# "dependencies"."chrome-devtools-frontend"
version = 
# "dependencies"."chrome-devtools-frontend"
resolved = 
# "dependencies"."chrome-devtools-frontend"
integrity = 
# "dependencies"."circular-json"
version = 
# "dependencies"."circular-json"
resolved = 
# "dependencies"."circular-json"
integrity = 
# "dependencies"."circular-json"
dev = 
# "dependencies"."cli-boxes"
version = 
# "dependencies"."cli-boxes"
resolved = 
# "dependencies"."cli-boxes"
integrity = 
# "dependencies"."cli-cursor"
version = 
# "dependencies"."cli-cursor"
resolved = 
# "dependencies"."cli-cursor"
integrity = 
# "dependencies"."cli-cursor"
dev = 
# "dependencies"."cli-width"
version = 
# "dependencies"."cli-width"
resolved = 
# "dependencies"."cli-width"
integrity = 
# "dependencies"."cli-width"
dev = 
# "dependencies"."cliui"
version = 
# "dependencies"."cliui"
resolved = 
# "dependencies"."cliui"
integrity = 
# "dependencies"."cliui"."dependencies"."ansi-regex"
version = 
# "dependencies"."cliui"."dependencies"."ansi-regex"
resolved = 
# "dependencies"."cliui"."dependencies"."ansi-regex"
integrity = 
# "dependencies"."cliui"."dependencies"."is-fullwidth-code-point"
version = 
# "dependencies"."cliui"."dependencies"."is-fullwidth-code-point"
resolved = 
# "dependencies"."cliui"."dependencies"."is-fullwidth-code-point"
integrity = 
# "dependencies"."cliui"."dependencies"."string-width"
version = 
# "dependencies"."cliui"."dependencies"."string-width"
resolved = 
# "dependencies"."cliui"."dependencies"."string-width"
integrity = 
# "dependencies"."cliui"."dependencies"."strip-ansi"
version = 
# "dependencies"."cliui"."dependencies"."strip-ansi"
resolved = 
# "dependencies"."cliui"."dependencies"."strip-ansi"
integrity = 
# "dependencies"."co"
version = 
# "dependencies"."co"
resolved = 
# "dependencies"."co"
integrity = 
# "dependencies"."co"
dev = 
# "dependencies"."code-point-at"
version = 
# "dependencies"."code-point-at"
resolved = 
# "dependencies"."code-point-at"
integrity = 
# "dependencies"."color-convert"
version = 
# "dependencies"."color-convert"
resolved = 
# "dependencies"."color-convert"
integrity = 
# "dependencies"."color-name"
version = 
# "dependencies"."color-name"
resolved = 
# "dependencies"."color-name"
integrity = 
# "dependencies"."colors"
version = 
# "dependencies"."colors"
resolved = 
# "dependencies"."colors"
integrity = 
# "dependencies"."commander"
version = 
# "dependencies"."commander"
resolved = 
# "dependencies"."commander"
integrity = 
# "dependencies"."commander"
dev = 
# "dependencies"."concat-map"
version = 
# "dependencies"."concat-map"
resolved = 
# "dependencies"."concat-map"
integrity = 
# "dependencies"."concat-map"
dev = 
# "dependencies"."concat-stream"
version = 
# "dependencies"."concat-stream"
resolved = 
# "dependencies"."concat-stream"
integrity = 
# "dependencies"."concat-stream"
dev = 
# "dependencies"."configstore"
version = 
# "dependencies"."configstore"
resolved = 
# "dependencies"."configstore"
integrity = 
# "dependencies"."contains-path"
version = 
# "dependencies"."contains-path"
resolved = 
# "dependencies"."contains-path"
integrity = 
# "dependencies"."contains-path"
dev = 
# "dependencies"."content-disposition"
version = 
# "dependencies"."content-disposition"
resolved = 
# "dependencies"."content-disposition"
integrity = 
# "dependencies"."content-disposition"
dev = 
# "dependencies"."content-type"
version = 
# "dependencies"."content-type"
resolved = 
# "dependencies"."content-type"
integrity = 
# "dependencies"."content-type"
dev = 
# "dependencies"."cookie"
version = 
# "dependencies"."cookie"
resolved = 
# "dependencies"."cookie"
integrity = 
# "dependencies"."cookie"
dev = 
# "dependencies"."cookie-signature"
version = 
# "dependencies"."cookie-signature"
resolved = 
# "dependencies"."cookie-signature"
integrity = 
# "dependencies"."cookie-signature"
dev = 
# "dependencies"."core-util-is"
version = 
# "dependencies"."core-util-is"
resolved = 
# "dependencies"."core-util-is"
integrity = 
# "dependencies"."create-error-class"
version = 
# "dependencies"."create-error-class"
resolved = 
# "dependencies"."create-error-class"
integrity = 
# "dependencies"."cross-spawn"
version = 
# "dependencies"."cross-spawn"
resolved = 
# "dependencies"."cross-spawn"
integrity = 
# "dependencies"."crypto-random-string"
version = 
# "dependencies"."crypto-random-string"
resolved = 
# "dependencies"."crypto-random-string"
integrity = 
# "dependencies"."css-select"
version = 
# "dependencies"."css-select"
resolved = 
# "dependencies"."css-select"
integrity = 
# "dependencies"."css-what"
version = 
# "dependencies"."css-what"
resolved = 
# "dependencies"."css-what"
integrity = 
# "dependencies"."currently-unhandled"
version = 
# "dependencies"."currently-unhandled"
resolved = 
# "dependencies"."currently-unhandled"
integrity = 
# "dependencies"."d"
version = 
# "dependencies"."d"
resolved = 
# "dependencies"."d"
integrity = 
# "dependencies"."d"
dev = 
# "dependencies"."debug"
version = 
# "dependencies"."debug"
resolved = 
# "dependencies"."debug"
integrity = 
# "dependencies"."debug-log"
version = 
# "dependencies"."debug-log"
resolved = 
# "dependencies"."debug-log"
integrity = 
# "dependencies"."debug-log"
dev = 
# "dependencies"."decamelize"
version = 
# "dependencies"."decamelize"
resolved = 
# "dependencies"."decamelize"
integrity = 
# "dependencies"."deep-extend"
version = 
# "dependencies"."deep-extend"
resolved = 
# "dependencies"."deep-extend"
integrity = 
# "dependencies"."deep-is"
version = 
# "dependencies"."deep-is"
resolved = 
# "dependencies"."deep-is"
integrity = 
# "dependencies"."deep-is"
dev = 
# "dependencies"."define-properties"
version = 
# "dependencies"."define-properties"
resolved = 
# "dependencies"."define-properties"
integrity = 
# "dependencies"."define-properties"
dev = 
# "dependencies"."deglob"
version = 
# "dependencies"."deglob"
resolved = 
# "dependencies"."deglob"
integrity = 
# "dependencies"."deglob"
dev = 
# "dependencies"."del"
version = 
# "dependencies"."del"
resolved = 
# "dependencies"."del"
integrity = 
# "dependencies"."del"
dev = 
# "dependencies"."depd"
version = 
# "dependencies"."depd"
resolved = 
# "dependencies"."depd"
integrity = 
# "dependencies"."depd"
dev = 
# "dependencies"."destroy"
version = 
# "dependencies"."destroy"
resolved = 
# "dependencies"."destroy"
integrity = 
# "dependencies"."destroy"
dev = 
# "dependencies"."devtools-timeline-model"
version = 
# "dependencies"."devtools-timeline-model"
resolved = 
# "dependencies"."devtools-timeline-model"
integrity = 
# "dependencies"."devtools-timeline-model"."dependencies"."chrome-devtools-frontend"
version = 
# "dependencies"."devtools-timeline-model"."dependencies"."chrome-devtools-frontend"
resolved = 
# "dependencies"."devtools-timeline-model"."dependencies"."chrome-devtools-frontend"
integrity = 
# "dependencies"."diff"
version = 
# "dependencies"."diff"
resolved = 
# "dependencies"."diff"
integrity = 
# "dependencies"."diff"
dev = 
# "dependencies"."doctrine"
version = 
# "dependencies"."doctrine"
resolved = 
# "dependencies"."doctrine"
integrity = 
# "dependencies"."doctrine"
dev = 
# "dependencies"."dom-serializer"
version = 
# "dependencies"."dom-serializer"
resolved = 
# "dependencies"."dom-serializer"
integrity = 
# "dependencies"."dom-serializer"."dependencies"."domelementtype"
version = 
# "dependencies"."dom-serializer"."dependencies"."domelementtype"
resolved = 
# "dependencies"."dom-serializer"."dependencies"."domelementtype"
integrity = 
# "dependencies"."domelementtype"
version = 
# "dependencies"."domelementtype"
resolved = 
# "dependencies"."domelementtype"
integrity = 
# "dependencies"."domhandler"
version = 
# "dependencies"."domhandler"
resolved = 
# "dependencies"."domhandler"
integrity = 
# "dependencies"."domutils"
version = 
# "dependencies"."domutils"
resolved = 
# "dependencies"."domutils"
integrity = 
# "dependencies"."dot-prop"
version = 
# "dependencies"."dot-prop"
resolved = 
# "dependencies"."dot-prop"
integrity = 
# "dependencies"."duplexer3"
version = 
# "dependencies"."duplexer3"
resolved = 
# "dependencies"."duplexer3"
integrity = 
# "dependencies"."ee-first"
version = 
# "dependencies"."ee-first"
resolved = 
# "dependencies"."ee-first"
integrity = 
# "dependencies"."ee-first"
dev = 
# "dependencies"."encodeurl"
version = 
# "dependencies"."encodeurl"
resolved = 
# "dependencies"."encodeurl"
integrity = 
# "dependencies"."encodeurl"
dev = 
# "dependencies"."entities"
version = 
# "dependencies"."entities"
resolved = 
# "dependencies"."entities"
integrity = 
# "dependencies"."error-ex"
version = 
# "dependencies"."error-ex"
resolved = 
# "dependencies"."error-ex"
integrity = 
# "dependencies"."es-abstract"
version = 
# "dependencies"."es-abstract"
resolved = 
# "dependencies"."es-abstract"
integrity = 
# "dependencies"."es-abstract"
dev = 
# "dependencies"."es-to-primitive"
version = 
# "dependencies"."es-to-primitive"
resolved = 
# "dependencies"."es-to-primitive"
integrity = 
# "dependencies"."es-to-primitive"
dev = 
# "dependencies"."es5-ext"
version = 
# "dependencies"."es5-ext"
resolved = 
# "dependencies"."es5-ext"
integrity = 
# "dependencies"."es5-ext"
dev = 
# "dependencies"."es6-iterator"
version = 
# "dependencies"."es6-iterator"
resolved = 
# "dependencies"."es6-iterator"
integrity = 
# "dependencies"."es6-iterator"
dev = 
# "dependencies"."es6-map"
version = 
# "dependencies"."es6-map"
resolved = 
# "dependencies"."es6-map"
integrity = 
# "dependencies"."es6-map"
dev = 
# "dependencies"."es6-set"
version = 
# "dependencies"."es6-set"
resolved = 
# "dependencies"."es6-set"
integrity = 
# "dependencies"."es6-set"
dev = 
# "dependencies"."es6-symbol"
version = 
# "dependencies"."es6-symbol"
resolved = 
# "dependencies"."es6-symbol"
integrity = 
# "dependencies"."es6-symbol"
dev = 
# "dependencies"."es6-weak-map"
version = 
# "dependencies"."es6-weak-map"
resolved = 
# "dependencies"."es6-weak-map"
integrity = 
# "dependencies"."es6-weak-map"
dev = 
# "dependencies"."escape-html"
version = 
# "dependencies"."escape-html"
resolved = 
# "dependencies"."escape-html"
integrity = 
# "dependencies"."escape-html"
dev = 
# "dependencies"."escape-string-regexp"
version = 
# "dependencies"."escape-string-regexp"
resolved = 
# "dependencies"."escape-string-regexp"
integrity = 
# "dependencies"."escope"
version = 
# "dependencies"."escope"
resolved = 
# "dependencies"."escope"
integrity = 
# "dependencies"."escope"
dev = 
# "dependencies"."eslint"
version = 
# "dependencies"."eslint"
resolved = 
# "dependencies"."eslint"
integrity = 
# "dependencies"."eslint"
dev = 
# "dependencies"."eslint"."dependencies"."strip-bom"
version = 
# "dependencies"."eslint"."dependencies"."strip-bom"
resolved = 
# "dependencies"."eslint"."dependencies"."strip-bom"
integrity = 
# "dependencies"."eslint"."dependencies"."strip-bom"
dev = 
# "dependencies"."eslint-config-standard"
version = 
# "dependencies"."eslint-config-standard"
resolved = 
# "dependencies"."eslint-config-standard"
integrity = 
# "dependencies"."eslint-config-standard"
dev = 
# "dependencies"."eslint-config-standard-jsx"
version = 
# "dependencies"."eslint-config-standard-jsx"
resolved = 
# "dependencies"."eslint-config-standard-jsx"
integrity = 
# "dependencies"."eslint-config-standard-jsx"
dev = 
# "dependencies"."eslint-import-resolver-node"
version = 
# "dependencies"."eslint-import-resolver-node"
resolved = 
# "dependencies"."eslint-import-resolver-node"
integrity = 
# "dependencies"."eslint-import-resolver-node"
dev = 
# "dependencies"."eslint-module-utils"
version = 
# "dependencies"."eslint-module-utils"
resolved = 
# "dependencies"."eslint-module-utils"
integrity = 
# "dependencies"."eslint-module-utils"
dev = 
# "dependencies"."eslint-plugin-import"
version = 
# "dependencies"."eslint-plugin-import"
resolved = 
# "dependencies"."eslint-plugin-import"
integrity = 
# "dependencies"."eslint-plugin-import"
dev = 
# "dependencies"."eslint-plugin-import"."dependencies"."doctrine"
version = 
# "dependencies"."eslint-plugin-import"."dependencies"."doctrine"
resolved = 
# "dependencies"."eslint-plugin-import"."dependencies"."doctrine"
integrity = 
# "dependencies"."eslint-plugin-import"."dependencies"."doctrine"
dev = 
# "dependencies"."eslint-plugin-node"
version = 
# "dependencies"."eslint-plugin-node"
resolved = 
# "dependencies"."eslint-plugin-node"
integrity = 
# "dependencies"."eslint-plugin-node"
dev = 
# "dependencies"."eslint-plugin-promise"
version = 
# "dependencies"."eslint-plugin-promise"
resolved = 
# "dependencies"."eslint-plugin-promise"
integrity = 
# "dependencies"."eslint-plugin-promise"
dev = 
# "dependencies"."eslint-plugin-react"
version = 
# "dependencies"."eslint-plugin-react"
resolved = 
# "dependencies"."eslint-plugin-react"
integrity = 
# "dependencies"."eslint-plugin-react"
dev = 
# "dependencies"."eslint-plugin-react"."dependencies"."doctrine"
version = 
# "dependencies"."eslint-plugin-react"."dependencies"."doctrine"
resolved = 
# "dependencies"."eslint-plugin-react"."dependencies"."doctrine"
integrity = 
# "dependencies"."eslint-plugin-react"."dependencies"."doctrine"
dev = 
# "dependencies"."eslint-plugin-standard"
version = 
# "dependencies"."eslint-plugin-standard"
resolved = 
# "dependencies"."eslint-plugin-standard"
integrity = 
# "dependencies"."eslint-plugin-standard"
dev = 
# "dependencies"."espree"
version = 
# "dependencies"."espree"
resolved = 
# "dependencies"."espree"
integrity = 
# "dependencies"."espree"
dev = 
# "dependencies"."esprima"
version = 
# "dependencies"."esprima"
resolved = 
# "dependencies"."esprima"
integrity = 
# "dependencies"."esprima"
dev = 
# "dependencies"."esquery"
version = 
# "dependencies"."esquery"
resolved = 
# "dependencies"."esquery"
integrity = 
# "dependencies"."esquery"
dev = 
# "dependencies"."esrecurse"
version = 
# "dependencies"."esrecurse"
resolved = 
# "dependencies"."esrecurse"
integrity = 
# "dependencies"."esrecurse"
dev = 
# "dependencies"."estraverse"
version = 
# "dependencies"."estraverse"
resolved = 
# "dependencies"."estraverse"
integrity = 
# "dependencies"."estraverse"
dev = 
# "dependencies"."esutils"
version = 
# "dependencies"."esutils"
resolved = 
# "dependencies"."esutils"
integrity = 
# "dependencies"."esutils"
dev = 
# "dependencies"."etag"
version = 
# "dependencies"."etag"
resolved = 
# "dependencies"."etag"
integrity = 
# "dependencies"."etag"
dev = 
# "dependencies"."event-emitter"
version = 
# "dependencies"."event-emitter"
resolved = 
# "dependencies"."event-emitter"
integrity = 
# "dependencies"."event-emitter"
dev = 
# "dependencies"."execa"
version = 
# "dependencies"."execa"
resolved = 
# "dependencies"."execa"
integrity = 
# "dependencies"."exit-hook"
version = 
# "dependencies"."exit-hook"
resolved = 
# "dependencies"."exit-hook"
integrity = 
# "dependencies"."exit-hook"
dev = 
# "dependencies"."express"
version = 
# "dependencies"."express"
resolved = 
# "dependencies"."express"
integrity = 
# "dependencies"."express"
dev = 
# "dependencies"."express"."dependencies"."debug"
version = 
# "dependencies"."express"."dependencies"."debug"
resolved = 
# "dependencies"."express"."dependencies"."debug"
integrity = 
# "dependencies"."express"."dependencies"."debug"
dev = 
# "dependencies"."fast-levenshtein"
version = 
# "dependencies"."fast-levenshtein"
resolved = 
# "dependencies"."fast-levenshtein"
integrity = 
# "dependencies"."fast-levenshtein"
dev = 
# "dependencies"."figures"
version = 
# "dependencies"."figures"
resolved = 
# "dependencies"."figures"
integrity = 
# "dependencies"."figures"
dev = 
# "dependencies"."file-entry-cache"
version = 
# "dependencies"."file-entry-cache"
resolved = 
# "dependencies"."file-entry-cache"
integrity = 
# "dependencies"."file-entry-cache"
dev = 
# "dependencies"."finalhandler"
version = 
# "dependencies"."finalhandler"
resolved = 
# "dependencies"."finalhandler"
integrity = 
# "dependencies"."finalhandler"
dev = 
# "dependencies"."finalhandler"."dependencies"."debug"
version = 
# "dependencies"."finalhandler"."dependencies"."debug"
resolved = 
# "dependencies"."finalhandler"."dependencies"."debug"
integrity = 
# "dependencies"."finalhandler"."dependencies"."debug"
dev = 
# "dependencies"."find-root"
version = 
# "dependencies"."find-root"
resolved = 
# "dependencies"."find-root"
integrity = 
# "dependencies"."find-root"
dev = 
# "dependencies"."find-up"
version = 
# "dependencies"."find-up"
resolved = 
# "dependencies"."find-up"
integrity = 
# "dependencies"."flat-cache"
version = 
# "dependencies"."flat-cache"
resolved = 
# "dependencies"."flat-cache"
integrity = 
# "dependencies"."flat-cache"
dev = 
# "dependencies"."foreach"
version = 
# "dependencies"."foreach"
resolved = 
# "dependencies"."foreach"
integrity = 
# "dependencies"."foreach"
dev = 
# "dependencies"."forwarded"
version = 
# "dependencies"."forwarded"
resolved = 
# "dependencies"."forwarded"
integrity = 
# "dependencies"."forwarded"
dev = 
# "dependencies"."fresh"
version = 
# "dependencies"."fresh"
resolved = 
# "dependencies"."fresh"
integrity = 
# "dependencies"."fresh"
dev = 
# "dependencies"."fs.realpath"
version = 
# "dependencies"."fs.realpath"
resolved = 
# "dependencies"."fs.realpath"
integrity = 
# "dependencies"."fs.realpath"
dev = 
# "dependencies"."function-bind"
version = 
# "dependencies"."function-bind"
resolved = 
# "dependencies"."function-bind"
integrity = 
# "dependencies"."function-bind"
dev = 
# "dependencies"."generate-function"
version = 
# "dependencies"."generate-function"
resolved = 
# "dependencies"."generate-function"
integrity = 
# "dependencies"."generate-function"
dev = 
# "dependencies"."generate-object-property"
version = 
# "dependencies"."generate-object-property"
resolved = 
# "dependencies"."generate-object-property"
integrity = 
# "dependencies"."generate-object-property"
dev = 
# "dependencies"."get-caller-file"
version = 
# "dependencies"."get-caller-file"
resolved = 
# "dependencies"."get-caller-file"
integrity = 
# "dependencies"."get-port"
version = 
# "dependencies"."get-port"
resolved = 
# "dependencies"."get-port"
integrity = 
# "dependencies"."get-port"
dev = 
# "dependencies"."get-stdin"
version = 
# "dependencies"."get-stdin"
resolved = 
# "dependencies"."get-stdin"
integrity = 
# "dependencies"."get-stream"
version = 
# "dependencies"."get-stream"
resolved = 
# "dependencies"."get-stream"
integrity = 
# "dependencies"."glob"
version = 
# "dependencies"."glob"
resolved = 
# "dependencies"."glob"
integrity = 
# "dependencies"."glob"
dev = 
# "dependencies"."globals"
version = 
# "dependencies"."globals"
resolved = 
# "dependencies"."globals"
integrity = 
# "dependencies"."globals"
dev = 
# "dependencies"."globby"
version = 
# "dependencies"."globby"
resolved = 
# "dependencies"."globby"
integrity = 
# "dependencies"."globby"
dev = 
# "dependencies"."got"
version = 
# "dependencies"."got"
resolved = 
# "dependencies"."got"
integrity = 
# "dependencies"."graceful-fs"
version = 
# "dependencies"."graceful-fs"
resolved = 
# "dependencies"."graceful-fs"
integrity = 
# "dependencies"."graceful-readlink"
version = 
# "dependencies"."graceful-readlink"
resolved = 
# "dependencies"."graceful-readlink"
integrity = 
# "dependencies"."graceful-readlink"
dev = 
# "dependencies"."growl"
version = 
# "dependencies"."growl"
resolved = 
# "dependencies"."growl"
integrity = 
# "dependencies"."growl"
dev = 
# "dependencies"."has"
version = 
# "dependencies"."has"
resolved = 
# "dependencies"."has"
integrity = 
# "dependencies"."has"
dev = 
# "dependencies"."has-ansi"
version = 
# "dependencies"."has-ansi"
resolved = 
# "dependencies"."has-ansi"
integrity = 
# "dependencies"."has-ansi"."dependencies"."ansi-regex"
version = 
# "dependencies"."has-ansi"."dependencies"."ansi-regex"
resolved = 
# "dependencies"."has-ansi"."dependencies"."ansi-regex"
integrity = 
# "dependencies"."has-flag"
version = 
# "dependencies"."has-flag"
resolved = 
# "dependencies"."has-flag"
integrity = 
# "dependencies"."hosted-git-info"
version = 
# "dependencies"."hosted-git-info"
resolved = 
# "dependencies"."hosted-git-info"
integrity = 
# "dependencies"."htmlparser2"
version = 
# "dependencies"."htmlparser2"
resolved = 
# "dependencies"."htmlparser2"
integrity = 
# "dependencies"."http-errors"
version = 
# "dependencies"."http-errors"
resolved = 
# "dependencies"."http-errors"
integrity = 
# "dependencies"."http-errors"
dev = 
# "dependencies"."iconv-lite"
version = 
# "dependencies"."iconv-lite"
resolved = 
# "dependencies"."iconv-lite"
integrity = 
# "dependencies"."ignore"
version = 
# "dependencies"."ignore"
resolved = 
# "dependencies"."ignore"
integrity = 
# "dependencies"."ignore"
dev = 
# "dependencies"."image-ssim"
version = 
# "dependencies"."image-ssim"
resolved = 
# "dependencies"."image-ssim"
integrity = 
# "dependencies"."import-lazy"
version = 
# "dependencies"."import-lazy"
resolved = 
# "dependencies"."import-lazy"
integrity = 
# "dependencies"."imurmurhash"
version = 
# "dependencies"."imurmurhash"
resolved = 
# "dependencies"."imurmurhash"
integrity = 
# "dependencies"."indent-string"
version = 
# "dependencies"."indent-string"
resolved = 
# "dependencies"."indent-string"
integrity = 
# "dependencies"."inflight"
version = 
# "dependencies"."inflight"
resolved = 
# "dependencies"."inflight"
integrity = 
# "dependencies"."inflight"
dev = 
# "dependencies"."inherits"
version = 
# "dependencies"."inherits"
resolved = 
# "dependencies"."inherits"
integrity = 
# "dependencies"."ini"
version = 
# "dependencies"."ini"
resolved = 
# "dependencies"."ini"
integrity = 
# "dependencies"."inquirer"
version = 
# "dependencies"."inquirer"
resolved = 
# "dependencies"."inquirer"
integrity = 
# "dependencies"."inquirer"
dev = 
# "dependencies"."inquirer"."dependencies"."ansi-regex"
version = 
# "dependencies"."inquirer"."dependencies"."ansi-regex"
resolved = 
# "dependencies"."inquirer"."dependencies"."ansi-regex"
integrity = 
# "dependencies"."inquirer"."dependencies"."ansi-regex"
dev = 
# "dependencies"."inquirer"."dependencies"."is-fullwidth-code-point"
version = 
# "dependencies"."inquirer"."dependencies"."is-fullwidth-code-point"
resolved = 
# "dependencies"."inquirer"."dependencies"."is-fullwidth-code-point"
integrity = 
# "dependencies"."inquirer"."dependencies"."is-fullwidth-code-point"
dev = 
# "dependencies"."inquirer"."dependencies"."string-width"
version = 
# "dependencies"."inquirer"."dependencies"."string-width"
resolved = 
# "dependencies"."inquirer"."dependencies"."string-width"
integrity = 
# "dependencies"."inquirer"."dependencies"."string-width"
dev = 
# "dependencies"."inquirer"."dependencies"."strip-ansi"
version = 
# "dependencies"."inquirer"."dependencies"."strip-ansi"
resolved = 
# "dependencies"."inquirer"."dependencies"."strip-ansi"
integrity = 
# "dependencies"."inquirer"."dependencies"."strip-ansi"
dev = 
# "dependencies"."interpret"
version = 
# "dependencies"."interpret"
resolved = 
# "dependencies"."interpret"
integrity = 
# "dependencies"."interpret"
dev = 
# "dependencies"."invert-kv"
version = 
# "dependencies"."invert-kv"
resolved = 
# "dependencies"."invert-kv"
integrity = 
# "dependencies"."ipaddr.js"
version = 
# "dependencies"."ipaddr.js"
resolved = 
# "dependencies"."ipaddr.js"
integrity = 
# "dependencies"."ipaddr.js"
dev = 
# "dependencies"."is-arrayish"
version = 
# "dependencies"."is-arrayish"
resolved = 
# "dependencies"."is-arrayish"
integrity = 
# "dependencies"."is-builtin-module"
version = 
# "dependencies"."is-builtin-module"
resolved = 
# "dependencies"."is-builtin-module"
integrity = 
# "dependencies"."is-callable"
version = 
# "dependencies"."is-callable"
resolved = 
# "dependencies"."is-callable"
integrity = 
# "dependencies"."is-callable"
dev = 
# "dependencies"."is-date-object"
version = 
# "dependencies"."is-date-object"
resolved = 
# "dependencies"."is-date-object"
integrity = 
# "dependencies"."is-date-object"
dev = 
# "dependencies"."is-finite"
version = 
# "dependencies"."is-finite"
resolved = 
# "dependencies"."is-finite"
integrity = 
# "dependencies"."is-fullwidth-code-point"
version = 
# "dependencies"."is-fullwidth-code-point"
resolved = 
# "dependencies"."is-fullwidth-code-point"
integrity = 
# "dependencies"."is-my-json-valid"
version = 
# "dependencies"."is-my-json-valid"
resolved = 
# "dependencies"."is-my-json-valid"
integrity = 
# "dependencies"."is-my-json-valid"
dev = 
# "dependencies"."is-npm"
version = 
# "dependencies"."is-npm"
resolved = 
# "dependencies"."is-npm"
integrity = 
# "dependencies"."is-obj"
version = 
# "dependencies"."is-obj"
resolved = 
# "dependencies"."is-obj"
integrity = 
# "dependencies"."is-path-cwd"
version = 
# "dependencies"."is-path-cwd"
resolved = 
# "dependencies"."is-path-cwd"
integrity = 
# "dependencies"."is-path-cwd"
dev = 
# "dependencies"."is-path-in-cwd"
version = 
# "dependencies"."is-path-in-cwd"
resolved = 
# "dependencies"."is-path-in-cwd"
integrity = 
# "dependencies"."is-path-in-cwd"
dev = 
# "dependencies"."is-path-inside"
version = 
# "dependencies"."is-path-inside"
resolved = 
# "dependencies"."is-path-inside"
integrity = 
# "dependencies"."is-path-inside"
dev = 
# "dependencies"."is-property"
version = 
# "dependencies"."is-property"
resolved = 
# "dependencies"."is-property"
integrity = 
# "dependencies"."is-property"
dev = 
# "dependencies"."is-redirect"
version = 
# "dependencies"."is-redirect"
resolved = 
# "dependencies"."is-redirect"
integrity = 
# "dependencies"."is-regex"
version = 
# "dependencies"."is-regex"
resolved = 
# "dependencies"."is-regex"
integrity = 
# "dependencies"."is-regex"
dev = 
# "dependencies"."is-resolvable"
version = 
# "dependencies"."is-resolvable"
resolved = 
# "dependencies"."is-resolvable"
integrity = 
# "dependencies"."is-resolvable"
dev = 
# "dependencies"."is-retry-allowed"
version = 
# "dependencies"."is-retry-allowed"
resolved = 
# "dependencies"."is-retry-allowed"
integrity = 
# "dependencies"."is-stream"
version = 
# "dependencies"."is-stream"
resolved = 
# "dependencies"."is-stream"
integrity = 
# "dependencies"."is-symbol"
version = 
# "dependencies"."is-symbol"
resolved = 
# "dependencies"."is-symbol"
integrity = 
# "dependencies"."is-symbol"
dev = 
# "dependencies"."is-utf8"
version = 
# "dependencies"."is-utf8"
resolved = 
# "dependencies"."is-utf8"
integrity = 
# "dependencies"."isarray"
version = 
# "dependencies"."isarray"
resolved = 
# "dependencies"."isarray"
integrity = 
# "dependencies"."isexe"
version = 
# "dependencies"."isexe"
resolved = 
# "dependencies"."isexe"
integrity = 
# "dependencies"."jpeg-js"
version = 
# "dependencies"."jpeg-js"
resolved = 
# "dependencies"."jpeg-js"
integrity = 
# "dependencies"."js-tokens"
version = 
# "dependencies"."js-tokens"
resolved = 
# "dependencies"."js-tokens"
integrity = 
# "dependencies"."js-tokens"
dev = 
# "dependencies"."js-yaml"
version = 
# "dependencies"."js-yaml"
resolved = 
# "dependencies"."js-yaml"
integrity = 
# "dependencies"."js-yaml"
dev = 
# "dependencies"."json-stable-stringify"
version = 
# "dependencies"."json-stable-stringify"
resolved = 
# "dependencies"."json-stable-stringify"
integrity = 
# "dependencies"."json-stable-stringify"
dev = 
# "dependencies"."json-stringify-safe"
version = 
# "dependencies"."json-stringify-safe"
resolved = 
# "dependencies"."json-stringify-safe"
integrity = 
# "dependencies"."json3"
version = 
# "dependencies"."json3"
resolved = 
# "dependencies"."json3"
integrity = 
# "dependencies"."json3"
dev = 
# "dependencies"."jsonify"
version = 
# "dependencies"."jsonify"
resolved = 
# "dependencies"."jsonify"
integrity = 
# "dependencies"."jsonify"
dev = 
# "dependencies"."jsonpointer"
version = 
# "dependencies"."jsonpointer"
resolved = 
# "dependencies"."jsonpointer"
integrity = 
# "dependencies"."jsonpointer"
dev = 
# "dependencies"."jsx-ast-utils"
version = 
# "dependencies"."jsx-ast-utils"
resolved = 
# "dependencies"."jsx-ast-utils"
integrity = 
# "dependencies"."jsx-ast-utils"
dev = 
# "dependencies"."latest-version"
version = 
# "dependencies"."latest-version"
resolved = 
# "dependencies"."latest-version"
integrity = 
# "dependencies"."lcid"
version = 
# "dependencies"."lcid"
resolved = 
# "dependencies"."lcid"
integrity = 
# "dependencies"."levn"
version = 
# "dependencies"."levn"
resolved = 
# "dependencies"."levn"
integrity = 
# "dependencies"."levn"
dev = 
# "dependencies"."lighthouse"
version = 
# "dependencies"."lighthouse"
resolved = 
# "dependencies"."lighthouse"
integrity = 
# "dependencies"."lighthouse"."dependencies"."ansi-regex"
version = 
# "dependencies"."lighthouse"."dependencies"."ansi-regex"
resolved = 
# "dependencies"."lighthouse"."dependencies"."ansi-regex"
integrity = 
# "dependencies"."lighthouse"."dependencies"."is-fullwidth-code-point"
version = 
# "dependencies"."lighthouse"."dependencies"."is-fullwidth-code-point"
resolved = 
# "dependencies"."lighthouse"."dependencies"."is-fullwidth-code-point"
integrity = 
# "dependencies"."lighthouse"."dependencies"."string-width"
version = 
# "dependencies"."lighthouse"."dependencies"."string-width"
resolved = 
# "dependencies"."lighthouse"."dependencies"."string-width"
integrity = 
# "dependencies"."lighthouse"."dependencies"."strip-ansi"
version = 
# "dependencies"."lighthouse"."dependencies"."strip-ansi"
resolved = 
# "dependencies"."lighthouse"."dependencies"."strip-ansi"
integrity = 
# "dependencies"."lighthouse"."dependencies"."yargs"
version = 
# "dependencies"."lighthouse"."dependencies"."yargs"
resolved = 
# "dependencies"."lighthouse"."dependencies"."yargs"
integrity = 
# "dependencies"."lighthouse-logger"
version = 
# "dependencies"."lighthouse-logger"
resolved = 
# "dependencies"."lighthouse-logger"
integrity = 
# "dependencies"."load-json-file"
version = 
# "dependencies"."load-json-file"
resolved = 
# "dependencies"."load-json-file"
integrity = 
# "dependencies"."locate-path"
version = 
# "dependencies"."locate-path"
resolved = 
# "dependencies"."locate-path"
integrity = 
# "dependencies"."locate-path"."dependencies"."path-exists"
version = 
# "dependencies"."locate-path"."dependencies"."path-exists"
resolved = 
# "dependencies"."locate-path"."dependencies"."path-exists"
integrity = 
# "dependencies"."lodash"
version = 
# "dependencies"."lodash"
resolved = 
# "dependencies"."lodash"
integrity = 
# "dependencies"."lodash._baseassign"
version = 
# "dependencies"."lodash._baseassign"
resolved = 
# "dependencies"."lodash._baseassign"
integrity = 
# "dependencies"."lodash._baseassign"
dev = 
# "dependencies"."lodash._basecopy"
version = 
# "dependencies"."lodash._basecopy"
resolved = 
# "dependencies"."lodash._basecopy"
integrity = 
# "dependencies"."lodash._basecopy"
dev = 
# "dependencies"."lodash._basecreate"
version = 
# "dependencies"."lodash._basecreate"
resolved = 
# "dependencies"."lodash._basecreate"
integrity = 
# "dependencies"."lodash._basecreate"
dev = 
# "dependencies"."lodash._getnative"
version = 
# "dependencies"."lodash._getnative"
resolved = 
# "dependencies"."lodash._getnative"
integrity = 
# "dependencies"."lodash._getnative"
dev = 
# "dependencies"."lodash._isiterateecall"
version = 
# "dependencies"."lodash._isiterateecall"
resolved = 
# "dependencies"."lodash._isiterateecall"
integrity = 
# "dependencies"."lodash._isiterateecall"
dev = 
# "dependencies"."lodash.cond"
version = 
# "dependencies"."lodash.cond"
resolved = 
# "dependencies"."lodash.cond"
integrity = 
# "dependencies"."lodash.cond"
dev = 
# "dependencies"."lodash.create"
version = 
# "dependencies"."lodash.create"
resolved = 
# "dependencies"."lodash.create"
integrity = 